{{- if .Values.minioCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minioCredentials.secretName | default "minio-creds" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minioCredentials.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minioCredentials.secretKey | quote }}
{{- end }}